[2024-11-28T11:02:25.719+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.insert_data manual__2024-11-28T11:02:21.767546+00:00 [queued]>
[2024-11-28T11:02:25.724+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: snowflake_demo_dag.insert_data manual__2024-11-28T11:02:21.767546+00:00 [queued]>
[2024-11-28T11:02:25.724+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:02:25.724+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 11
[2024-11-28T11:02:25.724+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-11-28T11:02:25.731+0000] {taskinstance.py:1383} INFO - Executing <Task(SnowflakeOperator): insert_data> on 2024-11-28 11:02:21.767546+00:00
[2024-11-28T11:02:25.733+0000] {standard_task_runner.py:55} INFO - Started process 250 to run task
[2024-11-28T11:02:25.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snowflake_demo_dag', 'insert_data', 'manual__2024-11-28T11:02:21.767546+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_dag.py', '--cfg-path', '/tmp/tmpi6xrjj3i']
[2024-11-28T11:02:25.736+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask insert_data
[2024-11-28T11:02:25.770+0000] {task_command.py:376} INFO - Running <TaskInstance: snowflake_demo_dag.insert_data manual__2024-11-28T11:02:21.767546+00:00 [running]> on host e85eb02d191d
[2024-11-28T11:02:25.802+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snowflake_demo_dag
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-11-28T11:02:21.767546+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-28T11:02:21.767546+00:00
[2024-11-28T11:02:25.803+0000] {sql.py:265} INFO - Executing: 
INSERT INTO demo_table (id, name, created_at)
VALUES (1, 'Airflow Demo', CURRENT_TIMESTAMP);
[2024-11-28T11:02:25.807+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:02:26.112+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:109: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  "pyarrow", installed_pyarrow_version, pandas_pyarrow_extra

[2024-11-28T11:02:26.245+0000] {base.py:71} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2024-11-28T11:02:26.246+0000] {connection.py:300} INFO - Snowflake Connector for Python Version: 3.0.4, Python Version: 3.7.15, Platform: Linux-6.10.4-linuxkit-aarch64-with-debian-11.5
[2024-11-28T11:02:26.246+0000] {connection.py:1013} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-28T11:02:26.246+0000] {connection.py:1023} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-11-28T11:02:26.247+0000] {connection.py:1030} INFO - Setting use_openssl_only mode to False
[2024-11-28T11:02:26.608+0000] {ssl_wrap_socket.py:101} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-11-28T11:02:26.869+0000] {cursor.py:806} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-11-28T11:02:26.951+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:02:26.952+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:02:26.953+0000] {sql.py:375} INFO - Running statement: INSERT INTO demo_table (id, name, created_at)
VALUES (1, 'Airflow Demo', CURRENT_TIMESTAMP);, parameters: None
[2024-11-28T11:02:26.953+0000] {cursor.py:806} INFO - query: [INSERT INTO demo_table (id, name, created_at) VALUES (1, 'Airflow Demo', CURRENT...]
[2024-11-28T11:02:27.231+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:02:27.231+0000] {sql.py:384} INFO - Rows affected: 1
[2024-11-28T11:02:27.231+0000] {snowflake.py:391} INFO - Rows affected: 1
[2024-11-28T11:02:27.231+0000] {snowflake.py:392} INFO - Snowflake query id: 01b8abf6-0001-3903-0006-ac5e0001a862
[2024-11-28T11:02:27.232+0000] {cursor.py:806} INFO - query: [COMMIT]
[2024-11-28T11:02:27.439+0000] {cursor.py:819} INFO - query execution done
[2024-11-28T11:02:27.439+0000] {cursor.py:962} INFO - Number of results in first chunk: 1
[2024-11-28T11:02:27.439+0000] {connection.py:605} INFO - closed
[2024-11-28T11:02:27.484+0000] {connection.py:608} INFO - No async queries seem to be running, deleting session
[2024-11-28T11:02:27.598+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=snowflake_demo_dag, task_id=insert_data, execution_date=20241128T110221, start_date=20241128T110225, end_date=20241128T110227
[2024-11-28T11:02:27.616+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-11-28T11:02:27.630+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
